language: android

android:
  components:
    - build-tools-29.0.2
    - android-29

    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

jdk:
  - oraclejdk8

before_install:
  - yes | sdkmanager "build-tools;29.0.2"

notifications:
  email: true

cache:
  directories:
    - $HOME/.m2

script:
  ./gradlew testDebugUnitTest testDebugUnitTestCoverage assembleDebug
