language: android

android:
  components:
    - build-tools-29.0.2
    - android-29

    - extra-google-m2repository
    - extra-android-m2repository

jdk:
  - oraclejdk8

before_install:
  - yes | sdkmanager --licenses

notifications:
  email: true

cache:
  directories:
    - $HOME/.m2

script:
    ./gradlew testDebugUnitTest testDebugUnitTestCoverage assembleDebug
